### ISSUE TITLE
pathIsAbsolute('C:/Users/'); is false

### ISSUE THREAD

**Issue by gabegattis** [sindresorhus/path-is-absolute#1]
The README has the example:

```
var pathIsAbsolute = require('path-is-absolute');

// Windows
pathIsAbsolute('C:/Users/');
//=> true
```

When I try that, it is false. I have to use the pathIsAbsolute.win32 method to get it to return true.

I am using path-is-absolute 1.0.0 with node v4 on linux.
Is that method only supposed to work if my actual environment is windows? The documentation is unclear.

**Comment by gabegattis** [comment]
So I found this
https://github.com/sindresorhus/path-is-absolute/blob/master/index.js#L18

which means that it is only supposed to work if I am running windows. So this is not a bug, but the README should make it clear that the example is not for generally validating windows paths, but for validating paths when running in a windows environment.

**Comment by sindresorhus** [comment]
This is just a polyfill for the native method. Any doc improvements should be requested on the Node.js issue tracker.

**Comment by gabegattis** [comment]
I'm not suggesting a change in behavior, just a clarification in the documentation.
